second try to fix the windows? function
Roblox/consul-cookbook pull request #1
Opened 2018-05-17 22:32 UTC by brnsampson

2018-05-17 23:13 UTC, ghost requested changes

2018-05-17 23:13 UTC, slynch-roblox commented on libraries/helpers.rb
> +      node.platform_family?('windows') ? true : false
Isn't the definition of a function that ends in question mark that it's a predicate? And doesn't that mean it returns true or false already?

2018-05-18 20:35 UTC, brnsampson commented
Currently I have verified the centos74 and windows 2016 working in kitchen with this cookbook

2018-05-18 22:10 UTC, ghost approved these changes
LGTM

2018-05-18 22:12 UTC, merged